USE sucos;

ALTER TABLE tbvendedores ADD PRIMARY KEY (MATRICULA);

DELETE FROM tbvendedores WHERE (MATRICULA = '00235');

DELETE FROM tbvendedores WHERE (MATRICULA = '00236');

ALTER TABLE tbvendedores ADD COLUMN (DATA_ADMISSÃO DATE);

ALTER TABLE tbvendedores ADD COLUMN (DE_FERIAS BIT);

INSERT INTO tbvendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSÃO, DE_FERIAS)
VALUES (
'00235','Mácio Almeida Silva',0.8,'2014-08-15',0);

INSERT INTO tbvendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSÃO, DE_FERIAS)
VALUES (
'00236','Cláudia Morais',0.8,'2013-09-17',1);

INSERT INTO tbvendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSÃO, DE_FERIAS)
VALUES (
'00237','Roberta Martins',0.11,'2017-03-18',1);

INSERT INTO tbvendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSÃO, DE_FERIAS)
VALUES (
'00238','Péricles Alvess',0.11,'2016-0-21',0);

SELECT * FROM tbvendedores;

